version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  auth-service:
    build: ./Service_auth
    ports:
      - "5000:5000
    depends_on:
      - mongodb
      
  project-service:
    build: ./project-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  task-service:
    build: ./task-service
    ports:
      - "5002:5002
    depends_on:
      - mongodb

  collaboration-service:
    build: ./collaboration-service
    ports:
      - "4005:4005"
  reporting-service:
  build: ./reporting-service
  ports:
    - "4006:4006"
